# Generated by Django 6.0.6 on 2026-06-27 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_number', models.PositiveIntegerField(help_text='The sequential number inside the subject (1, 2, 3 …).')),
                ('module_name', models.CharField(help_text='Human‑readable title of the module.', max_length=255)),
                ('file', models.FileField(help_text='The file that contains the module’s content (PDF, video, zip, …).', max_length=255, upload_to='modules/%Y/%m/%d/')),
                ('subject', models.ForeignKey(help_text='Subject that this module belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='slm.subject')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['subject', 'module_number'],
                'unique_together': {('subject', 'module_number')},
            },
        ),
    ]
