# Generated by Django 6.0.6 on 2026-06-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slm', '0002_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='year',
            field=models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Four')], default='1', help_text='Identifer for subject intended year.', max_length=1),
        ),
    ]
