# Generated by Django 6.0.6 on 2026-07-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slm', '0003_subject_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='extracted_html',
            field=models.TextField(blank=True, help_text='HTML version of the uploaded document – generated on upload.'),
        ),
        migrations.AlterField(
            model_name='module',
            name='file',
            field=models.FileField(help_text='The file that contains the module’s content (PDF, Word, PowerPoint).', max_length=255, upload_to='modules/%Y/%m/%d/'),
        ),
    ]
