# Generated by Django 6.0.6 on 2026-07-03 13:40

import django.db.models.deletion
import slm.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slm', '0004_module_extracted_html_alter_module_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Human‑readable title for the file.', max_length=255)),
                ('file', models.FileField(help_text='The uploaded document.', max_length=255, upload_to=slm.models.user_media_path)),
                ('extracted_html', models.TextField(blank=True, help_text='HTML version generated from the uploaded document (optional, usually filled by a background task).')),
                ('visibility', models.CharField(choices=[('PR', 'Private – only the owner can see it'), ('PU', 'Public – any logged‑in user can see it')], default='PR', help_text='Who may view this file.', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='Owner of the file.', on_delete=django.db.models.deletion.CASCADE, related_name='personal_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal Material',
                'verbose_name_plural': 'Personal Materials',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['visibility'], name='idx_personal_visibility')],
            },
        ),
    ]
