# Generated by Django 6.0.6 on 2026-07-07 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slm', '0005_personalmaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(help_text='The exact text that the user highlighted.', max_length=255)),
                ('answer', models.JSONField(blank=True, help_text='Two‑part answer from the AI (simplified & technical).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(help_text='The module the highlighted term belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='highlight_answers', to='slm.module')),
            ],
            options={
                'verbose_name': 'Highlight answer',
                'verbose_name_plural': 'Highlight answers',
                'ordering': ['-created_at'],
                'unique_together': {('module', 'query')},
            },
        ),
    ]
