# Generated by Django 6.0.6 on 2026-07-08 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slm', '0005_personalmaterial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(help_text='Exact highlighted text (lower‑cased).', max_length=255)),
                ('answer_simplified', models.TextField(blank=True, help_text='Simplified explanation.', null=True)),
                ('answer_technical', models.TextField(blank=True, help_text='Technical explanation.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlight_answers', to='slm.module')),
                ('owner', models.ForeignKey(help_text='User that asked the question – guarantees a private cache.', on_delete=django.db.models.deletion.CASCADE, related_name='highlight_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Highlight answer',
                'verbose_name_plural': 'Highlight answers',
                'ordering': ['-created_at'],
                'unique_together': {('module', 'query', 'owner')},
            },
        ),
    ]
