# Generated by Django 6.0.6 on 2026-07-07 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slm', '0006_highlightanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlightanswer',
            name='answer_simplified',
            field=models.TextField(blank=True, help_text='Simplified explanation.', null=True),
        ),
        migrations.AddField(
            model_name='highlightanswer',
            name='answer_technical',
            field=models.TextField(blank=True, help_text='Technical explanation.', null=True),
        ),
        migrations.AlterField(
            model_name='highlightanswer',
            name='answer',
            field=models.JSONField(blank=True, help_text='(Deprecated) Two‑part answer.', null=True),
        ),
        migrations.AlterField(
            model_name='highlightanswer',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlight_answers', to='slm.module'),
        ),
        migrations.AlterField(
            model_name='highlightanswer',
            name='query',
            field=models.CharField(help_text='Exact highlighted text.', max_length=255),
        ),
    ]
