# Generated by Django 6.0.6 on 2026-07-13 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slm', '0006_highlightanswer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='highlightanswer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='highlightanswer',
            name='personal_material',
            field=models.ForeignKey(blank=True, help_text='PersonalMaterial the answer belongs to (null when it belongs to a module).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highlight_answers', to='slm.personalmaterial'),
        ),
        migrations.AlterField(
            model_name='highlightanswer',
            name='module',
            field=models.ForeignKey(blank=True, help_text='Module the answer belongs to (null when it belongs to a personal material).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highlight_answers', to='slm.module'),
        ),
        migrations.AlterUniqueTogether(
            name='highlightanswer',
            unique_together={('module', 'personal_material', 'query', 'owner')},
        ),
    ]
