# Generated by Django 6.0.6 on 2026-08-09 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slm', '0008_module_created_at_module_is_archived_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(help_text='Exact highlighted text (lower‑cased).', max_length=255)),
                ('note', models.TextField(blank=True, help_text='Free‑form annotation written by the user.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(blank=True, help_text='Module the annotation belongs to (null for personal material).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highlight_annotations', to='slm.module')),
                ('owner', models.ForeignKey(help_text='User that created the annotation.', on_delete=django.db.models.deletion.CASCADE, related_name='highlight_annotations', to=settings.AUTH_USER_MODEL)),
                ('personal_material', models.ForeignKey(blank=True, help_text='Personal material the annotation belongs to (null for module).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highlight_annotations', to='slm.personalmaterial')),
            ],
            options={
                'verbose_name': 'Highlight annotation',
                'verbose_name_plural': 'Highlight annotations',
                'ordering': ['-created_at'],
                'unique_together': {('module', 'personal_material', 'query', 'owner')},
            },
        ),
    ]
