# Generated by Django 6.0.6 on 2026-08-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slm', '0009_highlightannotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='visibility',
            field=models.CharField(choices=[('PR', 'Private – only the owner can see it'), ('PU', 'Public – any logged‑in user can see it')], default='PR', max_length=2),
        ),
    ]
