# Generated by Django 6.0.6 on 2026-08-13 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slm', '0010_module_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='visibility',
        ),
    ]
