# Generated by Django 6.0.6 on 2026-08-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slm', '0011_remove_module_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='year',
            field=models.CharField(choices=[('2', 'Second'), ('3', 'Third')], default='2', help_text='Identifer for subject intended year.', max_length=1),
        ),
    ]
