# Generated by Django 5.2.17 on 2026-08-24 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slm', '0012_alter_subject_year'),
    ]

    operations = []
