# Generated by Django 6.0.6 on 2026-08-26 12:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slm', '0013_alter_highlightannotation_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='highlightannotation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='highlightanswer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='highlightannotation',
            name='end_offset',
            field=models.IntegerField(blank=True, help_text='Character offset where the annotation ends (exclusive).', null=True),
        ),
        migrations.AddField(
            model_name='highlightannotation',
            name='start_offset',
            field=models.IntegerField(blank=True, help_text='Character offset where the annotation starts.', null=True),
        ),
        migrations.AddField(
            model_name='highlightanswer',
            name='end_offset',
            field=models.IntegerField(blank=True, help_text='Character offset where the highlight ends (exclusive).', null=True),
        ),
        migrations.AddField(
            model_name='highlightanswer',
            name='start_offset',
            field=models.IntegerField(blank=True, help_text='Character offset where the highlight starts in the extracted HTML.', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='highlightannotation',
            unique_together={('module', 'personal_material', 'query', 'owner', 'start_offset', 'end_offset')},
        ),
        migrations.AlterUniqueTogether(
            name='highlightanswer',
            unique_together={('module', 'personal_material', 'query', 'owner', 'start_offset', 'end_offset')},
        ),
    ]
