# Generated by Django 6.0.5 on 2026-07-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_birth_date_remove_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='karma',
            field=models.IntegerField(default=0, help_text='Points earned from helpful posts and replies. Starts at 0.'),
        ),
    ]
