# Generated by Django 6.0.6 on 2026-07-31 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_user_program_remove_user_student_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
