# Generated by Django 6.0.6 on 2026-08-01 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide the announcement without deleting it.', verbose_name='Active')),
                ('start_date', models.DateTimeField(blank=True, help_text='If set, the announcement is shown only after this date/time.', null=True, verbose_name='Start date')),
                ('end_date', models.DateTimeField(blank=True, help_text='If set, the announcement stops being shown after this date/time.', null=True, verbose_name='End date')),
                ('author', models.ForeignKey(blank=True, help_text='User that created the announcement (staff).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-created_at'],
            },
        ),
    ]
