# Generated by Django 6.0.6 on 2026-08-09 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_pushsubscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
