# Generated by Django 6.0.6 on 2026-08-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_delete_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='program',
            field=models.CharField(blank=True, default='Information Technology', max_length=100, verbose_name='Program / Course'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='year_level',
            field=models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year')], max_length=20, verbose_name='Year Level'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='department',
            field=models.CharField(blank=True, default='CCS', max_length=100, verbose_name='Department'),
        ),
    ]
