# Generated by Django 6.0.6 on 2026-08-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_studentprofile_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, help_text='Require a one-time code from an authenticator app during login.', verbose_name='two-factor authentication enabled'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_secret',
            field=models.CharField(blank=True, default='', help_text='Base32 secret used for TOTP generation.', max_length=64, verbose_name='two-factor secret'),
        ),
    ]
