# Generated by Django 6.0.6 on 2026-08-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_user_two_factor_enabled_user_two_factor_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='year_level',
            field=models.CharField(choices=[('2nd Year', '2nd Year'), ('3rd Year', '3rd Year')], max_length=20, verbose_name='Year Level'),
        ),
    ]
