# Generated by Django 6.0.6 on 2026-08-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_studentprofile_year_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='True when the user has clicked the verification link sent to their e‑mail.', verbose_name='email verified'),
        ),
    ]
