# Generated by Django 5.2.17 on 2026-08-24 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_user_email_verified'),
    ]

    operations = []
