# Generated by Django 6.1 on 2026-09-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_pushsubscription_id_alter_studentprofile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_forum_visited',
            field=models.BooleanField(default=False, help_text='Whether the user has visited the Discussion Forum.'),
        ),
    ]
