# Generated by Django 6.1 on 2026-10-05 01:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_pushsubscription_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='forum_notifications_last_read',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
