# Generated by Django 5.2.17 on 2026-08-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
