# Generated by Django 5.2.17 on 2026-08-24 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment or bullying'), ('inappropriate', 'Inappropriate content'), ('misinformation', 'Misinformation'), ('other', 'Other')], max_length=50),
        ),
    ]
