# Generated by Django 6.0.6 on 2026-07-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_post_flag_reason_post_is_deleted_reply_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
