"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^pnd!-+l5abcn+($yh+u*52ovk%safdcb$mc5w+b)%+jyu-*y%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'account',
    'forum',
    'aihelper',
    'slm',
    'axes',
    'django_ratelimit',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware',
    "account.middleware.RequireLatestConsentMiddleware",
    'slm.middleware.NoCacheForDynamicPagesMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'core.middleware.IdleTimeoutMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'account.context_processors.user_groups',
                'account.context_processors.vapid_key',
                'forum.context_processors.unread_notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        "OPTIONS": {"min_length": 8},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = "account.User"

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',
    "account.backends.EmailOrUsernameModelBackend",
    "django.contrib.auth.backends.ModelBackend",
]

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.PyMemcacheCache',
        'LOCATION': '127.0.0.1:11211',
    },
    'axes_cache': {
        'BACKEND': 'django.core.cache.backends.memcached.PyMemcacheCache',
        'LOCATION': '127.0.0.1:11211',
    }
}


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'          # where collectstatic puts the files
STATICFILES_DIRS = [
    BASE_DIR / "static",                         # <-- your top‑level static folder
]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# myproject/settings.py
LOGIN_REDIRECT_URL = 'account:dashboard' 
LOGOUT_REDIRECT_URL = 'account:landing'

# --- Policy versioning -------------------------------------------------
POLICY_VERSION = "1.0"
POLICY_EFFECTIVE_DATE = "2026-04-01"      # YYYY‑MM‑DD format

OLLAMA_API_KEY = ""
OLLAMA_HOST = ""
OLLAMA_MODEL = ""

OPENAI_API_KEY = "OPENAI_API_KEY"          
OPENAI_MODEL   = "gpt-4o-mini"

PWA_SW_VERSION = "20260814"

VAPID_PUBLIC_KEY  = ""
VAPID_PRIVATE_KEY = ""

# settings.py

# Use the standard SMTP backend
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Host and port for your SMTP provider (e.g., Mailgun, SendGrid, Gmail, AWS SES)
EMAIL_HOST = ''
EMAIL_PORT = 587  # Use 587 for TLS, or 465 for SSL

# Authentication details
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''

# Security settings (Use True for one, keep the other False)
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

# Default sender address
DEFAULT_FROM_EMAIL = 'EduAlly <no-reply@yourdomain.com>'

# ── Axes configuration ─────────────────────────────────────────────────────
# All values are optional – the defaults are safe – but we set them
# explicitly so you can see what is happening.
from datetime import timedelta
AXES_LOCKOUT_PARAMETERS = [
    ["username", "ip_address", "user_agent"],
]
AXES_FAILURE_LIMIT = 5             # how many bad tries before lock‑out
AXES_COOLOFF_TIME = timedelta(minutes=15)   # 15 min block
AXES_USE_ATTEMPT_EXPIRATION = True
AXES_RESET_ON_SUCCESS = True          # clear counter on a successful login
AXES_CACHE = 'axes_cache'
# (Optional) If you sit behind a proxy that sets X‑Forwarded‑For, tell
# Axes which header contains the real client IP:
# AXES_PROXY_ORDER = ('HTTP_X_FORWARDED_FOR', 'REMOTE_ADDR')

# --------------------------------------------------------------
# Google OAuth2 configuration
# --------------------------------------------------------------
# You must create a Google OAuth client at https://console.cloud.google.com/apis/credentials
#   – Set "Authorized redirect URIs" to:  http://<your‑domain>/account/login/google/callback/
#   – For local development: http://127.0.0.1:8000/account/login/google/callback/
#
# Then copy the generated client ID / secret here.
#
GOOGLE_CLIENT_ID = "YOUR_GOOGLE_CLIENT_ID"
GOOGLE_CLIENT_SECRET = "YOUR_GOOGLE_CLIENT_SECRET"

# Build the absolute URL that Google will redirect back to.
# If you use `django.contrib.sites` you could build it dynamically,
# but a simple literal works fine for most projects.
GOOGLE_OAUTH_REDIRECT_URI = "http://127.0.0.1:8000/account/login/google/callback/"

SESSION_COOKIE_AGE = 30 * 60          # seconds (30 min)
SESSION_SAVE_EVERY_REQUEST = True    # refresh the expiry on each request (sliding window)
IDLE_TIMEOUT = 30 * 60

try:          # pragma: no‑cover   (makes test coverage ignore the try/except)
    from .settings_local import *   # noqa: F403,F401
except ImportError:               # No local file → keep defaults
    pass