# Generated by Django 6.1 on 2026-09-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aihelper', '0002_alter_conversation_id_alter_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='source_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='message',
            name='source_metadata',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='message',
            name='source_type',
            field=models.CharField(choices=[('slm', 'SLM'), ('general', 'General Knowledge')], default='general', max_length=20),
        ),
    ]
