# Generated by Django 6.1 on 2026-09-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aihelper', '0003_message_source_label_message_source_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='source_type',
            field=models.CharField(blank=True, choices=[('slm', 'SLM'), ('general', 'General Knowledge')], default=None, max_length=20, null=True),
        ),
    ]
